### ISSUE TITLE
Wario Land 2

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#3] opened 2018-06-21 20:56 UTC
Game resets back to the main menu as soon as gameplay is reached, just after Wario wakes up
![2018-06-21-215452_](https://user-images.githubusercontent.com/32330689/41745126-dd4a92ac-759d-11e8-981a-0563dd55bdd8.png)

**Comment by georgehb** [comment] 2018-06-21 21:02
Also Main menu is incorrect
![2018-06-21-215844_](https://user-images.githubusercontent.com/32330689/41745287-59607afa-759e-11e8-962f-8a4c7d71b044.png)

mGBA for comparison
![2018-06-21-220025_](https://user-images.githubusercontent.com/32330689/41745434-d3428214-759e-11e8-9898-09a012c8c238.png)

**Comment by philj56** [comment] 2018-06-23 15:18
The reset appears to have been fixed, probably by the rom banking fix in 0b03b63b28cd85d9f0f09615cae7dcd21587fb03. Not sure about the main menu for now

**Comment by georgehb** [comment] 2018-11-14 22:41
broken again in 2f2f0fa81f1d150de53963fefa34810debb5ee41
black screen after main menu

**Comment by philj56** [comment] 2018-12-04 17:41
> broken again in 2f2f0fa
black screen after main menu

This is fixed in 4eecf22eca2e4790cb6fa030f15d7b67a398a809. It was caused by various LCDSTAT interrupts being broken, e.g. the HBLANK interrupt not being called.

**Comment by philj56** [comment] 2019-04-21 15:05
Fixed in 4bc7da7a6e2dec75ea2741485a9284dba2f695ee.

**Closed as completed by philj56** 2019-04-21 15:05 UTC
Labels: bug
